### ISSUE TITLE
provide more information on the evaluation stage

### ISSUE THREAD

**Issue by trnamanh12** [giangbang/RL-final-project-AIT-3007#1]
anh có thể thêm thông tin về giai đoạn evaluation được không ạ? ví dụ như một file evaluation.py sẽ được sử dụng để đánh giá agent của em và agent của ( anh và thầy ) ạ

**Comment by giangbang** [comment]
mình sẽ up thêm code eval vào một file mới nhé.

**Comment by giangbang** [comment]
Mình đã update code demo evaluation vào file `eval.py`.
