### ISSUE TITLE
Thay đổi môi trường trong bài tập lớn

### ISSUE THREAD

**Issue by CTA2004** [giangbang/RL-final-project-AIT-3007#2]
Dạ em thưa anh là hiện tại nhóm chúng em muốn thay đổi biến môi trường từ:
env = battle_v4.env(map_size=45, render_mode="rgb_array")
sang 
env = battle_v4.env(map_size=45, minimap_mode=True, step_reward=-0.005, 
                        dead_penalty=-0.1, attack_penalty=-0.05, attack_opponent_reward=0.2,
                        max_cycles=2000, extra_features=False, render_mode="rgb_array")
thì có được không ạ. Em cảm ơn.

**Comment by giangbang** [comment]
được em nhé, lúc train em có thể thêm gì cũng được, nhưng report cuối kỳ phải eval trên môi trường ban đầu mặc định
