### ISSUE TITLE
Code eval.py không LIÊM!!!!

### ISSUE THREAD

**Issue by sambt22022517** [giangbang/RL-final-project-AIT-3007#4]
Thầy ơi, code eval.py của thầy có vấn đề ạ.
Nếu em để bên red là red.pt của thầy và blue là mô hình của em
![image](https://github.com/user-attachments/assets/26d4fd54-9063-4fbc-83d9-9e901ba96f9b)
thì kết quả là red.pt thắng model của em.
![image](https://github.com/user-attachments/assets/d71c2311-e5ac-4287-8dd1-af7b7060316f)

Nhưng nếu em đổi ngược lại, tức red là model của em và blue là red.pt
![image](https://github.com/user-attachments/assets/f0b66ab3-422a-46cb-822c-588c400ef500)
thì kết quả lại là model của em thắng red.pt ạ.
![image](https://github.com/user-attachments/assets/1e9a7bc0-47c4-4fd9-9290-fffccb63af5e)

Thầy có thể xem lại code file eval.py được không ạ?

**Comment by giangbang** [comment]
Hi em,

Model red.pt chỉ đc train trên data của đội đỏ thôi, nên không có gì đảm bảo là nó hoạt động tốt khi điều khiển đội xanh. Vì thế mình có nhấn mạnh ở trong readme:
> You should control _blue_ agents when evaluating.

Ngoài ra, hàm eval khá nhiễu và có vẻ bị bias về phía đội đỏ một chút: mình eval 2 random policy đấu với nhau 30 ván (giá trị default), bên xanh thắng 26%  và bên đỏ thắng khoảng 36%. Mình tăng số eval episode lên 100 thì kết quả vẫn giữ nguyên loanh quanh đó. Vì thế, mình thêm 1 rule mới khi quyết định thắng/thua để loại nhiễu này như sau: 

Luật cũ: team nào có số agent lớn hơn thì thắng
Luật mới: team nào có số agent lớn hơn team kia ít nhất 5 thì thắng.  (cf 7cda8751c1674ef5a188c6acbea6ee48571e9192)

Trên luật mới này, 2 random agent đấu với nhau đều có tỉ lệ thắng là 0%. 

Ngoài ra, mình có public cả code eval và weight của mô hình, nếu em phát hiện trong code có chỗ nào chưa liêm như em nói thì có thể raise issue lên trên này.

**Comment by sambt22022517** [comment]
Xét về mặt phần thường thì cả 2 trường hợp, mô hình của em đều dương và lớn hơn đối thủ khá nhiều ạ.
Do trong môi trường chỉ có kill_opponent là reward dương và đủ lớn để tạo ra cách biệt kiểu này, nên chẳng phải để có được phần thưởng lớn như vậy thì mô hình phải kill được nhiều lính của đối phương chứ ạ
![image](https://github.com/user-attachments/assets/8e1a3f20-92ff-4676-9685-1240d4c554e6)

**Comment by giangbang** [comment]
Hi em, 

Có vẻ đoạn test winrate đang có vấn đề thật. Em check thử code eval mới #5 xem nhé.

Làm tốt đấy :D
